name: Check README for Francesca

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for my name in README.md
        run: |
          if ! grep -q "Francesca" README.md; then
            echo "ERROR: README.md must contain your name!"
            exit 1
          fi

